version: '3.3'
services: 
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "4000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube
      - ~/sonarqube_data:/opt/sonarqube/data
    networks:
      - jenkins-network