version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:jdk11
    container_name: jenkins
    # restart: always
    volumes: 
        - ~/jenkins_home:/var/jenkins_home
    networks:
      - jenkins-network

  load-balancer:
    depends_on:
      - jenkins
    # restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    ports:
       - "80:80"
       - "443:443"
    networks:
      - jenkins-network

volumes:
  sonarqube_data:
networks:
  jenkins-network:
     driver: bridge
